/*
 * @Author: 崔浩然
 * @Email：cuihaoran@hualala.com
 * @Date: 2022-08-08 16:40:24
 * @Description: 页面/组件/功能的描述
 * @FilePath: /vue3-ts-cms/auto-imports.d.ts
 */
// Generated by 'unplugin-auto-import'
export {}
declare global {}
